# Generated by Django 5.0.1 on 2024-01-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0002_alter_studentcourse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='students',
            new_name='student',
        ),
    ]
